services:

    mysql:
        image: mysql:latest
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: tpnote
            MYSQL_PASSWORD: root
        ports:
            - "3306:3306"
        volumes:
            - mysql_data:/var/lib/mysql:rw

    postgres:
        image: postgres:16-alpine
        environment:
            POSTGRES_DB: app
            POSTGRES_PASSWORD: "!ChangeMe!"
            POSTGRES_USER: app
        ports:
            - "5432:5432"
        volumes:
            - pg_data:/var/lib/postgresql/data:rw

    mailhog:
        image: mailhog/mailhog
        ports:
            - "1025:1025"
            - "8481:8025"

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        environment:
            PMA_HOST: mysql
            PMA_USER: root
            PMA_PASSWORD: root
        ports:
            - "8981:80"
        depends_on:
            - mysql

volumes:
    pg_data:
    mysql_data:
